=== aldl1910/XML/Clientes/clientes.dtd
<!ELEMENT clientes (sede+)*>
<!ELEMENT sede (direccion+|empleado|Fecha|Descripcion?|codcliente)*>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT codcliente (numero|coste|resumen?|plazo)*>
<!ATTLIST codcliente codigo CDATA #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== aldl1910/XML/Clientes/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="A0007891">
        <direccion></direccion>
        <empleado></empleado>
        <Fecha></Fecha>
        <Descripcion></Descripcion>
        <codcliente codigo="AAA-456">
            <numero></numero>
            <coste></coste>
            <resumen></resumen>
            <plazo></plazo>
        </codcliente>
    </sede>
</clientes>
